### PR TITLE
Support build multiple architecture docker image: `x86_64`, `arm64`

### PR DESCRIPTION
**Pull request by mrproliu**
Support pushing multiple architecture docker images to the registry. For now, the GHA hasn't `arm64` instance, so I checked in the local machine and it works well.

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
This is for image building only, right?

**Comment by mrproliu** [comment]
Yes, it works for building the docker image.

**Comment by wu-sheng** [comment]
Is `arm64` also working for `aarm`? Apple sillicon

**Comment by mrproliu** [comment]
No, Apple is not supported.

**Pull request merged**
