### PR TITLE
Add license and let it could automatically generate

### PR DESCRIPTION
**Pull request by mrproliu**
1. update the dependency licenses
2. integrate with [skywalking-eyes](https://github.com/apache/skywalking-eyes), let it could generate the license automatically.
3. Add to the CI, so it can check the dependency license in each PR. 

@kezhenxu94 Please help to check the license generate code, there have some duplicated codes with eyes, not all of them. Maybe we could let the eyes generate it?

### CODE REVIEW

**Comment by wu-sheng** [comment]
@kezhenxu94 @mrproliu  We may need to discuss whether is generating license reasonable, and what should be the policy.

Should we open a discussion separate in main repo about this before take any action?

**Comment by mrproliu** [comment]
> Should we open a discussion separate in main repo about this before take any action?

Sure. In my case, It could help me quickly generate the licenses file, and reduce the number of steps in the release process.

**Comment by wu-sheng** [comment]
Should we close this?

**Comment by mrproliu** [comment]
Yes. closed.

**Pull request closed without merging**
