### PR TITLE
Introduce Log module

### PR DESCRIPTION
**Pull request by mrproliu**

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think you need a required task to pass CI.

**Comment by wu-sheng** [comment]
Please make sure you have clear comments for your public methods.

**Comment by wu-sheng** [comment]
Updating asf file would help. It only works aftet merge.

**Comment by mrproliu** [comment]
Ok, Should I need to change the `required_status_checks` as a new name separate name to avoid duplicate job names in this PR? And create another PR to rename this job name?

**Comment by wu-sheng** [comment]
I can't right now. You have to add  a mock task to pass the required tasks.

**Comment by wu-sheng** [comment]
Then you could change the required tasks with it.

**Comment by kezhenxu94** [comment]
> Ok, Should I need to change the `required_status_checks` as a new name separate name to avoid duplicate job names in this PR? And create another PR to rename this job name?

I don’t consider that as “duplicate job name” as some of them are with matrix name and only one is “Build and Test”

**Comment by kezhenxu94** [comment]
“CI” is a too general name and will result in a situation where we have another workflow that is also required to pass before merging, then how do you name that workflow?

**Comment by mrproliu** [comment]
Sure, I changed back to the name to "Build and Test". It works for me, just thought it looked a little weird.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
