### PR TITLE
Support OpenSSL library and add protocol and IsSSL labels in metrics

### PR DESCRIPTION
**Pull request by mrproliu**
* Analyze protocol when the data is in the connection
* Support for analyzing protocols that use the OpenSSL library program
* Add the `protocol` and `is_ssl` labels to the metrics when uploading to the backend

### CODE REVIEW

**Comment by wu-sheng** [comment]
> Add the protocol and is_ssl labels to the metrics when uploading to the backend

What are `protocol` and `is_ssl`'s values in the SSL case? What are in no-SSL case?

**Comment by mrproliu** [comment]
We only could analyze the protocol with plaintext. In SSL/TLS, we only could get the plaintext from the library probes. 

> What are protocol and is_ssl's values in the SSL case? 

the protocol is the analysis result. the protocol value could be `http`, `dns`, etc. And the `is_ssl` value is `true`.

> What are in no-SSL case?

the protocol is the same as the `SSL` case. And the `is_ssl` value is `false`.

**Comment by wu-sheng** [comment]
> We only could analyze the protocol with plaintext. In SSL/TLS, we only could get the plaintext from the library probes.

Yes, that is the purpose of SSL.

> the protocol is the analysis result. the protocol value could be http, dns, etc. And the is_ssl value is true.

Do we support `HTTP` `DNS` protocols recognition already?

**Comment by mrproliu** [comment]
> Do we support `HTTP` `DNS` protocols recognition already?

Yes, I have referenced the protocol analysis in [pixie](https://github.com/pixie-io/pixie).

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
