### PR TITLE
Update `LabelValue` obtain pod information function to add default value parameter

### PR DESCRIPTION
**Pull request by mrproliu**

### CODE REVIEW

**Comment by wu-sheng** [comment]
So, this means, select the first value of given keys, if all are null, fall into default value?

**Comment by mrproliu** [comment]
Yes.

**Comment by wu-sheng** [comment]
I would suggest rename this to valueOfFirstNotNullLabel. default value is fine as a parameter.

**Comment by mrproliu** [comment]
We already have the `LabelValue` function as you said(`valueOfFirstNotNullLabel`), but there is no default value parameter, should I just add the default value parameter in the `LabelValue`?

**Comment by wu-sheng** [comment]
We don't support overload?

**Comment by mrproliu** [comment]
Yes, I use a structure to implement the functions, and overload is not supported in the Golang structure.

**Comment by wu-sheng** [comment]
Then it is better to change the old function through add a new parameter.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
